using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;
using System.IO;
using System.Diagnostics;
using System.Net;

namespace AccountingMS.Forms
{
    public partial class formFoaterCustmer : Form
    {
        accountingEntities db = new accountingEntities();
        //fatoraCustmer pdffatora = new fatoraCustmer();
        public formFoaterCustmer()
        {
            InitializeComponent();

            AccountingMS.accountingEntities dbContext = new AccountingMS.accountingEntities();
     
            dbContext.fatoraCustmers.Load();
            // This line of code is generated by Data Source Configuration Wizard
            fatoraDateDateEdit.EditValue = DateTime.Now;
           // gridControl1.DataSource = dbContext.fatoraCustmers.Local.ToBindingList();
        }

        private void btnSave_Click(object sender, EventArgs e)
        {

            if (fatoraPathButtonEdit.Text != "" && fatoraTitelTextEdit.Text != "")
            {


                //if (Directory.Exists(fatoraPathButtonEdit.Text))
                //{
                string newPath = "\\upload\\" + supNoTextEdite.Text + DateTime.Now.ToString("yyyy-MM-dd hh-mm-ss");
                //  var pdffatora = db.fatoraCustmers.Add(this.fatoraCust);
                fatoraCustmer pdffatora = new fatoraCustmer();
                pdffatora.fatoraDate =Convert.ToDateTime( fatoraDateDateEdit.EditValue);
                pdffatora.supNo =Convert.ToInt16 (supNoTextEdite.EditValue);
                pdffatora.custNo = Convert.ToInt16 (custNoTextEdit.Tag);
                pdffatora.fatoraTitel = fatoraTitelTextEdit.EditValue.ToString();
                if (fatoraDescTextEdit.Text  != "") { pdffatora.fatoraDesc = fatoraDescTextEdit.EditValue.ToString(); }
               
                pdffatora.fatoraPath = newPath+".pdf";
                db.fatoraCustmers.Add(pdffatora);
                db.SaveChanges();
                fillgridcontrol();

                File.Copy(fatoraPathButtonEdit.Text, Application.StartupPath +"\\"+ newPath + ".pdf", true);
                MessageBox.Show("تم الحفظ بنجاح");
                fatoraDateDateEdit.EditValue = DateTime.Now;
                fatoraTitelTextEdit.EditValue = "";
                fatoraDescTextEdit.EditValue = "";
                fatoraPathButtonEdit.EditValue = "";

                //}
            }
            else
            {
                MessageBox.Show("من فضلك حدد الفاتورة أولا");
            }



        }

        public void SearchCustmer(int custmerNo, string custmerName)
        {
            custNoTextEdit.Text = custmerName;
            custNoTextEdit.Tag = custmerNo;

            supNoTextEdite.Properties.DataSource = (from custmer in db.tblSupplyMains.ToList() select new { supNo = custmer.supNo });
            supNoTextEdite.Properties.DisplayMember = "supNo";
            supNoTextEdite.Properties.ValueMember = "supNo";

        }

        private void fatoraPathButtonEdit_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            OpenFileDialog op = new OpenFileDialog();

            op.Filter = "pdf files (*.PDF)|*.pdf";
            op.FilterIndex = 1;
            op.RestoreDirectory = true;

            if (op.ShowDialog() == DialogResult.OK)
            {
                fatoraPathButtonEdit.Text = op.FileName;

            }
        }

        private void repositoryItemButtonEdit1_ButtonClick(object sender, DevExpress.XtraEditors.Controls.ButtonPressedEventArgs e)
        {
            var openpdf= Application.StartupPath + gridView1.GetRowCellValue(gridView1.FocusedRowHandle, "fatoraPath");
            openpdf = WebUtility.UrlDecode(openpdf.ToString());
            //Process.Start((openpdf));

            ProcessStartInfo startInfo = new ProcessStartInfo(@openpdf);
            Process.Start(startInfo);


        }

        private void formFoaterCustmer_Load(object sender, EventArgs e)
        {
            fillgridcontrol();
        }

        void fillgridcontrol()
        {
            gridControl1.DataSource = db.fatoraCustmers.ToList();
        }
    }
}
