//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cashingEmp
    {
        public int id { get; set; }
        public Nullable<int> empID { get; set; }
        public string typePay { get; set; }
        public Nullable<System.DateTime> dateAncestor { get; set; }
        public Nullable<double> BasicSalary { get; set; }
        public Nullable<System.TimeSpan> ExtraHours { get; set; }
        public Nullable<double> valueExtraHours { get; set; }
        public Nullable<double> numberOfDays { get; set; }
        public Nullable<double> valueAbsence { get; set; }
        public Nullable<System.TimeSpan> NumberAbsence { get; set; }
        public Nullable<double> DelayValue { get; set; }
        public Nullable<double> mealAllowance { get; set; }
        public Nullable<double> TransferAllowance { get; set; }
        public Nullable<double> OtherRewards { get; set; }
        public Nullable<double> ancestor { get; set; }
        public Nullable<double> Insurances { get; set; }
        public Nullable<double> OtherDiscounts { get; set; }
        public Nullable<double> NetSalary { get; set; }
        public Nullable<int> entBoxNo { get; set; }
        public Nullable<int> entRefNo { get; set; }
        public Nullable<byte> entCurrency { get; set; }
        public Nullable<short> entCurChange { get; set; }
        public Nullable<short> entBrnId { get; set; }
        public byte entStatus { get; set; }
        public Nullable<System.DateTime> entDate { get; set; }
        public Nullable<System.DateTime> entReverseConstraintDate { get; set; }
        public string entDesc { get; set; }
    }
}
