//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class DrawerPeriodTransSummeryItem
    {
        public int ID { get; set; }
        public int ProcessType { get; set; }
        public int ProcessCount { get; set; }
        public double ProcessSum { get; set; }
    
        public virtual DrawerPeriod DrawerPeriod { get; set; }
    }
}
