//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class fatoraCustmer
    {
        public int id { get; set; }
        public int supNo { get; set; }
        public Nullable<System.DateTime> fatoraDate { get; set; }
        public string fatoraTitel { get; set; }
        public string fatoraDesc { get; set; }
        public string fatoraPath { get; set; }
        public int custNo { get; set; }
    }
}
