//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeAndDelayRegulationMinutesTable
    {
        public int id { get; set; }
        public System.DateTime fromMin { get; set; }
        public Nullable<System.DateTime> ToMin { get; set; }
        public Nullable<System.DateTime> ToMinute { get; set; }
        public Nullable<bool> calculate { get; set; }
    }
}
