//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class OvertimeAndDelayRegulation
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<double> DiscountValuePerHour { get; set; }
        public Nullable<double> ExtraValuePerHour { get; set; }
        public string notes { get; set; }
        public Nullable<double> AbsenceValue { get; set; }
    }
}
