//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalaryRegulationExtension
    {
        public int id { get; set; }
        public Nullable<double> SalaryRegulation { get; set; }
        public Nullable<int> SalaryRegulationID { get; set; }
        public Nullable<int> SalaryExtensionID { get; set; }
    }
}
