//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxDeclaration
    {
        public int ID { get; set; }
        public int Code { get; set; }
        public System.DateTime FromDate { get; set; }
        public System.DateTime ToDate { get; set; }
        public string Notes { get; set; }
        public double Sales { get; set; }
        public double SalesReturn { get; set; }
        public double SalesTax { get; set; }
        public double SalesTotal { get; set; }
        public double SalesReturnTotal { get; set; }
        public double SalesTaxTotal { get; set; }
        public double Purchase { get; set; }
        public double PurchaseReturn { get; set; }
        public double PurchaseTax { get; set; }
        public double PurchaseTotal { get; set; }
        public double PurchaseReturnTotal { get; set; }
        public double PurchaseTaxTotal { get; set; }
        public double CurrentTax { get; set; }
        public Nullable<short> BranchID { get; set; }
    }
}
