//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccountBox
    {
        public short id { get; set; }
        public int boxNo { get; set; }
        public long boxAccNo { get; set; }
        public Nullable<byte> boxCurrency { get; set; }
        public string boxName { get; set; }
        public Nullable<int> boxCelling { get; set; }
        public Nullable<short> boxBrnId { get; set; }
    }
}
