//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblAccount
    {
        public int id { get; set; }
        public long accNo { get; set; }
        public string accName { get; set; }
        public Nullable<byte> accCat { get; set; }
        public Nullable<int> accParent { get; set; }
        public byte accLevel { get; set; }
        public byte accType { get; set; }
        public Nullable<byte> accCurrency { get; set; }
        public Nullable<short> accBrnId { get; set; }
        public Nullable<byte> accStatus { get; set; }
        public Nullable<int> ParentID { get; set; }
    }
}
