//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblBarcode
    {
        public int id { get; set; }
        public string brcNo { get; set; }
        public int brcPrdMsurId { get; set; }
        public short brcBrnId { get; set; }
    }
}
