//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCustomerInvoice
    {
        public int invId { get; set; }
        public int invCstId { get; set; }
        public int invSupId { get; set; }
        public short invBrnId { get; set; }
    }
}
