//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblControl
    {
        public short cntId { get; set; }
        public byte cntucNo { get; set; }
        public string cntName { get; set; }
        public string cntCaption { get; set; }
        public string cntCaptionEn { get; set; }
    }
}
