//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblEntrySub
    {
        public int id { get; set; }
        public int entNo { get; set; }
        public Nullable<long> entAccNo { get; set; }
        public string entAccName { get; set; }
        public Nullable<int> entBoxNo { get; set; }
        public string entDesc { get; set; }
        public Nullable<double> entDebit { get; set; }
        public Nullable<double> entCredit { get; set; }
        public Nullable<double> entDebitFrgn { get; set; }
        public Nullable<double> entCreditFrgn { get; set; }
        public Nullable<byte> entTaxPercent { get; set; }
        public Nullable<double> entTaxPrice { get; set; }
        public Nullable<byte> entCurrency { get; set; }
        public Nullable<short> entCurChange { get; set; }
        public Nullable<int> entCusNo { get; set; }
        public string entCusName { get; set; }
        public Nullable<byte> entStatus { get; set; }
        public Nullable<System.DateTime> entDate { get; set; }
        public Nullable<byte> entView { get; set; }
        public Nullable<byte> entIsMain { get; set; }
        public Nullable<byte> entEqfal { get; set; }
        public Nullable<short> entBrnId { get; set; }
        public string entTaxNumber { get; set; }
        public string invoNum { get; set; }
        public string supplyName { get; set; }
        public Nullable<System.DateTime> entInvoDate { get; set; }
    }
}
