//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblGroupStr
    {
        public int id { get; set; }
        public int grpNo { get; set; }
        public string grpName { get; set; }
        public long grpAccNo { get; set; }
        public byte grpCurrency { get; set; }
        public Nullable<long> grpSalesAccNo { get; set; }
        public Nullable<long> grpCostAccNo { get; set; }
        public Nullable<long> grpDscntAccNo { get; set; }
        public Nullable<long> grpSalesRtrnAccNo { get; set; }
        public Nullable<long> grpCostRtrnAccNo { get; set; }
        public Nullable<short> grpBrnId { get; set; }
        public byte grpStatus { get; set; }
        public Nullable<long> grpPurchaseAccNo { get; set; }
        public Nullable<long> grpPurchaseRtrnAccNo { get; set; }
    }
}
