//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblInvStoreSub
    {
        public int id { get; set; }
        public int invMainId { get; set; }
        public string invBarcode { get; set; }
        public int invPrdId { get; set; }
        public int invPrdMsurId { get; set; }
        public int invPrdGrpId { get; set; }
        public double invQuanStr { get; set; }
        public double invQuanAvl { get; set; }
        public double invQuanDefr { get; set; }
        public double invPriceAvrg { get; set; }
        public double invPriceDefr { get; set; }
        public double invPriceTotal { get; set; }
        public double invSalePrice { get; set; }
        public double invSalePriceTotal { get; set; }
    }
}
