//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrderSub
    {
        public int ordId { get; set; }
        public int ordMainId { get; set; }
        public int ordPrdId { get; set; }
        public int ordMsurId { get; set; }
        public string ordPrdBarcode { get; set; }
        public double ordQuantity { get; set; }
        public Nullable<double> ordPrice { get; set; }
        public Nullable<double> ordPriceSale { get; set; }
        public Nullable<byte> ordTaxPercent { get; set; }
        public Nullable<double> ordTax { get; set; }
        public Nullable<double> ordTotal { get; set; }
        public string ordDesc { get; set; }
        public string ordNote { get; set; }
        public System.DateTime ordDate { get; set; }
        public short ordBrnId { get; set; }
        public byte ordStatus { get; set; }
    }
}
