//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductQtyOpn
    {
        public int qtyId { get; set; }
        public short qtyStrId { get; set; }
        public int qtyPrdId { get; set; }
        public int qtyPrdMsurId { get; set; }
        public double qtyPrice { get; set; }
        public double qtyQuantity { get; set; }
        public System.DateTime qtyDate { get; set; }
        public short qtyBranchId { get; set; }
        public byte qtyStatus { get; set; }
        public Nullable<System.DateTime> qtyExpireDate { get; set; }
    }
}
