//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrdPriceQuan
    {
        public int prId { get; set; }
        public int prPrdId { get; set; }
        public double pr1 { get; set; }
        public double pr2 { get; set; }
        public double pr3 { get; set; }
        public double prQuantity1 { get; set; }
        public double prQuantity2 { get; set; }
        public double prQuantity3 { get; set; }
        public Nullable<short> prdBrnId { get; set; }
        public bool prStatus { get; set; }
    }
}
