//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPrdExpirateQuan
    {
        public int expId { get; set; }
        public short expStrid { get; set; }
        public int expPrdId { get; set; }
        public int expPrdMsurId { get; set; }
        public byte expPrdMsurStatus { get; set; }
        public int expPrdPriceQuanId { get; set; }
        public double expPrdPrice { get; set; }
        public double expQuan { get; set; }
        public System.DateTime expPrdDate { get; set; }
        public System.DateTime expDate { get; set; }
        public short expBrnId { get; set; }
        public byte expStatus { get; set; }
        public Nullable<int> expMainId { get; set; }
    }
}
