//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductPriceOffer
    {
        public int id { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<bool> ActiveShow { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> ExpireDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> State { get; set; }
        public Nullable<int> DiscountType { get; set; }
        public Nullable<double> TotalFatora { get; set; }
        public string DiscountName { get; set; }
        public string StateName { get; set; }
        public Nullable<System.DateTime> CustmerStartDate { get; set; }
        public Nullable<System.DateTime> CustmerEndDate { get; set; }
        public string ShowName { get; set; }
        public string prdNo { get; set; }
    }
}
