//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProduct
    {
        public int id { get; set; }
        public string prdNo { get; set; }
        public string prdName { get; set; }
        public string prdNameEng { get; set; }
        public int prdGrpNo { get; set; }
        public string prdDesc { get; set; }
        public bool prdSaleTax { get; set; }
        public bool prdPriceTax { get; set; }
        public Nullable<short> prdBrnId { get; set; }
        public byte prdStatus { get; set; }
        public double ReorderLevel { get; set; }
        public double MaxLevel { get; set; }
        public bool prdPurchaseTax { get; set; }
        public bool Suspended { get; set; }
    }
}
