//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProductQunatity
    {
        public int id { get; set; }
        public int prdId { get; set; }
        public Nullable<double> prdQuantity { get; set; }
        public Nullable<double> prdSubQuantity { get; set; }
        public Nullable<double> prdSubQuantity3 { get; set; }
        public Nullable<short> prdStrId { get; set; }
        public Nullable<short> prdBrnId { get; set; }
        public byte prdStatus { get; set; }
    }
}
