//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRoleControl
    {
        public short rcId { get; set; }
        public short fkRoleId { get; set; }
        public byte fkucNo { get; set; }
        public short fkControlId { get; set; }
    }
}
