//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRepresentativeStore
    {
        public int id { get; set; }
        public Nullable<int> RepId { get; set; }
        public Nullable<int> StoreId { get; set; }
        public string ProudctName { get; set; }
        public Nullable<double> repPrice { get; set; }
        public Nullable<int> repQuntity { get; set; }
        public Nullable<int> ProudctNo { get; set; }
        public string barcode { get; set; }
        public string RepName { get; set; }
    }
}
