//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblRepresentative
    {
        public int id { get; set; }
        public int repNo { get; set; }
        public string repName { get; set; }
        public long repAccNo { get; set; }
        public byte repCurrency { get; set; }
        public string repPhnNo { get; set; }
        public string repAddress { get; set; }
        public string repEmail { get; set; }
        public short repBrnId { get; set; }
        public byte repStatus { get; set; }
        public string repPassword { get; set; }
        public string repMainName { get; set; }
        public Nullable<bool> repEnble { get; set; }
        public string repMemo { get; set; }
        public string repRate { get; set; }
        public string repMobail { get; set; }
        public Nullable<bool> repTypeRete { get; set; }
        public string repValuRate { get; set; }
    }
}
