//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblSetting
    {
        public short ID { get; set; }
        public bool supplyA4CustomRprt { get; set; }
        public bool supplyCashierCustomRprt { get; set; }
        public bool teReportVocherCustom { get; set; }
        public bool teReportReciptCustom { get; set; }
        public bool teReportEntryCustom { get; set; }
        public bool showRprtPurchaseHeader { get; set; }
        public bool showRprtSaleHeader { get; set; }
        public bool rprtOrderA4CustomRpt { get; set; }
        public bool supplyRetuA4CustomRprt { get; set; }
        public byte rprtSupplyCustomType { get; set; }
        public string MachineName { get; set; }
        public bool IsInvoiceRound { get; set; }
        public bool showPrdQtyMssg { get; set; }
        public bool PayPartInvoValue { get; set; }
        public bool isSendToECR { get; set; }
        public string ecrPort { get; set; }
        public bool GroupProductsInInvoices { get; set; }
        public bool defaultPrintOnSave { get; set; }
        public bool ShowPrintMssg { get; set; }
        public bool GroupWeightProdInInvoices { get; set; }
        public bool ShowResetMssg { get; set; }
        public string defaultPrinterSettings { get; set; }
        public bool defaultSalePriceFloar { get; set; }
        public long defaultBox { get; set; }
        public short defaultBank { get; set; }
        public bool AllowSaveInvoInBeforeDate { get; set; }
        public byte printA4 { get; set; }
        public short defaultStrId { get; set; }
        public bool ReadFormScaleBarcode { get; set; }
        public byte BarcodeLength { get; set; }
        public string ScaleBarcodePrefix { get; set; }
        public byte ProductCodeLength { get; set; }
        public byte ValueCodeLength { get; set; }
        public byte ReadMode { get; set; }
        public bool IgnoreCheckDigit { get; set; }
        public short DivideValueBy { get; set; }
        public string defaultPrinterBarcode { get; set; }
        public bool prdPriceTax { get; set; }
        public bool supPrdLastPrice { get; set; }
        public short tsDefaultSalePriceAndBuy { get; set; }
        public bool autoSupplyTarhel { get; set; }
        public bool ShowlayoutControlCarData { get; set; }
        public bool TaxReadMode { get; set; }
        public bool InvType { get; set; }
        public byte dfltAccLevel { get; set; }
        public string WelcomeMessage { get; set; }
        public short BranchID { get; set; }
        public bool ordersPrintPreview { get; set; }
        public bool ordersShowPrintMssg { get; set; }
        public string ordersPrinter { get; set; }
        public string ordersVoucherStr { get; set; }
        public string ordersExecuteStr { get; set; }
        public string ordersReceiptStr { get; set; }
        public string ordersVoucherStrPlu { get; set; }
        public string ordersExecuteStrPlu { get; set; }
        public string ordersReceiptStrPlu { get; set; }
        public bool CalcTaxAfterDiscount { get; set; }
        public bool AutoBarcode { get; set; }
        public Nullable<bool> UserDrawerPeriods { get; set; }
        public bool ShowlayoutControlOtherData { get; set; }
        public string employees { get; set; }
        public Nullable<bool> emp { get; set; }
    }
}
