//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockTransMain
    {
        public int stcId { get; set; }
        public int stcNo { get; set; }
        public Nullable<int> stcRefNo { get; set; }
        public short stcStrIdFrom { get; set; }
        public short stcStrIdTo { get; set; }
        public string stcDesc { get; set; }
        public System.DateTime stcDate { get; set; }
        public short stcBrnId { get; set; }
        public short stcUserId { get; set; }
    }
}
