//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblStockTransSub
    {
        public int stcId { get; set; }
        public int stcMainId { get; set; }
        public int stcPrdId { get; set; }
        public int stcMsurId { get; set; }
        public double stcQuantity { get; set; }
        public System.DateTime stcDate { get; set; }
        public short stcBrnId { get; set; }
    }
}
