//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class TimeTable
    {
        public int id { get; set; }
        public string name { get; set; }
        public Nullable<System.TimeSpan> time_attendance { get; set; }
        public Nullable<System.TimeSpan> Time_leave { get; set; }
        public Nullable<bool> ShiftType { get; set; }
        public Nullable<int> ShiftId { get; set; }
    }
}
