//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_unit
    {
        public string prdName { get; set; }
        public string ppmMsurName { get; set; }
        public int id { get; set; }
        public int ppmId { get; set; }
        public string ppmBarcode1 { get; set; }
        public string grpName { get; set; }
    }
}
