//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_FixedAssets
    {
        public int id { get; set; }
        public string assetsName { get; set; }
        public string assetsNameE { get; set; }
        public Nullable<double> PurchaseValue { get; set; }
        public Nullable<System.DateTime> datePurchase { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> stopAssets { get; set; }
        public Nullable<bool> CreateImplicitSubAccount { get; set; }
        public Nullable<int> originalAccount { get; set; }
        public Nullable<int> DepreciationAccount { get; set; }
        public Nullable<int> currency { get; set; }
        public Nullable<bool> equalizer { get; set; }
        public Nullable<double> DepreciationRate { get; set; }
        public Nullable<double> currentValue { get; set; }
        public string originalPhoto { get; set; }
        public Nullable<double> DepreciationDay { get; set; }
        public Nullable<int> CountDay { get; set; }
        public Nullable<double> DepreciationNow { get; set; }
        public Nullable<double> DepreciationYeer { get; set; }
        public string AssetName { get; set; }
        public string AssetNameE { get; set; }
        public string DepreciationNameE { get; set; }
        public string DepreciationName { get; set; }
        public string curName { get; set; }
    }
}
