//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_repComm
    {
        public string DisplayName { get; set; }
        public double commission { get; set; }
        public string Notes { get; set; }
        public Nullable<bool> isActive { get; set; }
        public string prdName { get; set; }
        public string strName { get; set; }
        public string repName { get; set; }
        public int id { get; set; }
        public int RepId { get; set; }
        public int PrdId { get; set; }
        public int RepCommission { get; set; }
        public int StorId { get; set; }
        public int idrepcom { get; set; }
    }
}
