//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EntriesNotificationAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EntriesNotificationAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.EntriesNotificationAr", typeof(EntriesNotificationAr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد : .
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قيد يومي.
        /// </summary>
        internal static string dailyVocher {
            get {
                return ResourceManager.GetString("dailyVocher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من حذف القيد اليومي رقم : {0}؟.
        /// </summary>
        internal static string delEntMssg {
            get {
                return ResourceManager.GetString("delEntMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف القيد اليومي رقم : {0} بنجاح..
        /// </summary>
        internal static string delEntSuccessMssg {
            get {
                return ResourceManager.GetString("delEntSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من حذف سند قبض رقم : {0}؟.
        /// </summary>
        internal static string delRcptMssg {
            get {
                return ResourceManager.GetString("delRcptMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف سند قبض رقم : {0} بنجاح..
        /// </summary>
        internal static string delRcptSuccessMssg {
            get {
                return ResourceManager.GetString("delRcptSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من حذف سند صرف رقم : {0}؟.
        /// </summary>
        internal static string delVchrMssg {
            get {
                return ResourceManager.GetString("delVchrMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف سند صرف رقم : {0} بنجاح..
        /// </summary>
        internal static string delVchrSuccessMssg {
            get {
                return ResourceManager.GetString("delVchrSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا لقد تم إستخدام السند رقم {0} مسبقا..
        /// </summary>
        internal static string entErrorMssg {
            get {
                return ResourceManager.GetString("entErrorMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيد اليومي رقم :  {0}.
        /// </summary>
        internal static string entSuccessMssg {
            get {
                return ResourceManager.GetString("entSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند صرف.
        /// </summary>
        internal static string paymentVocher {
            get {
                return ResourceManager.GetString("paymentVocher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من ترحيل السندات؟.
        /// </summary>
        internal static string phaseMssg {
            get {
                return ResourceManager.GetString("phaseMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ترحيل السندات بنجاح.
        /// </summary>
        internal static string phaseSuccessMssg {
            get {
                return ResourceManager.GetString("phaseSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد طباعة السند رقم : {0}؟.
        /// </summary>
        internal static string printMssg {
            get {
                return ResourceManager.GetString("printMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا لقد تم إستخدام سند قبض رقم {0} مسبقا..
        /// </summary>
        internal static string rcptErrorMssg {
            get {
                return ResourceManager.GetString("rcptErrorMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند الصرف  رقم :  {0}.
        /// </summary>
        internal static string rcptSuccessMssg {
            get {
                return ResourceManager.GetString("rcptSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند قبض.
        /// </summary>
        internal static string receiptVocher {
            get {
                return ResourceManager.GetString("receiptVocher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من إلغاء الترحيل سند رقم : {0}؟.
        /// </summary>
        internal static string undoPhaseMssg {
            get {
                return ResourceManager.GetString("undoPhaseMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء ترحيل السند رقم : {0} بنجاح..
        /// </summary>
        internal static string undoPhaseSuccesMssg {
            get {
                return ResourceManager.GetString("undoPhaseSuccesMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا هناك خطاء في المبالغ التي ادخلتها.
        /// </summary>
        internal static string validateAmountMssg {
            get {
                return ResourceManager.GetString("validateAmountMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا لقد تم إستخدام سند صرف رقم {0} مسبقا..
        /// </summary>
        internal static string vchrErrorMssg {
            get {
                return ResourceManager.GetString("vchrErrorMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سند الصرف  رقم :  {0}.
        /// </summary>
        internal static string vchrSuccessMssg {
            get {
                return ResourceManager.GetString("vchrSuccessMssg", resourceCulture);
            }
        }
    }
}
