//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class formAddSupplyVocherEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal formAddSupplyVocherEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.formAddSupplyVocherEn", typeof(formAddSupplyVocherEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        internal static string barCheckItem1_Caption {
            get {
                return ResourceManager.GetString("barCheckItem1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string bbiSelect_Text {
            get {
                return ResourceManager.GetString("bbiSelect.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add fractions.
        /// </summary>
        internal static string BtnAddFraction {
            get {
                return ResourceManager.GetString("BtnAddFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Product (F9).
        /// </summary>
        internal static string btnAddProduct {
            get {
                return ResourceManager.GetString("btnAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnClose_Text {
            get {
                return ResourceManager.GetString("btnClose.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDeleteRow {
            get {
                return ResourceManager.GetString("btnDeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fraction Deduction.
        /// </summary>
        internal static string BtnDscnFraction {
            get {
                return ResourceManager.GetString("BtnDscnFraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancellation.
        /// </summary>
        internal static string btnECRcancel {
            get {
                return ResourceManager.GetString("btnECRcancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string btnECRsend {
            get {
                return ResourceManager.GetString("btnECRsend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Price (F7).
        /// </summary>
        internal static string btnEditPrice_Text {
            get {
                return ResourceManager.GetString("btnEditPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Quantity(F6).
        /// </summary>
        internal static string btnEditQuantity_Text {
            get {
                return ResourceManager.GetString("btnEditQuantity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid credit card (F11).
        /// </summary>
        internal static string btnPaidCreditShortcut_Text {
            get {
                return ResourceManager.GetString("btnPaidCreditShortcut.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase quotation (F8).
        /// </summary>
        internal static string btnPrdPrice_Text {
            get {
                return ResourceManager.GetString("btnPrdPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price conversion.
        /// </summary>
        internal static string btnPriceTrans_Text {
            get {
                return ResourceManager.GetString("btnPriceTrans.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print the previous bill.
        /// </summary>
        internal static string btnPrintPrevious_Text {
            get {
                return ResourceManager.GetString("btnPrintPrevious.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreash Product.
        /// </summary>
        internal static string btnRefreashProduct_Text {
            get {
                return ResourceManager.GetString("btnRefreashProduct.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset(F5).
        /// </summary>
        internal static string btnReset_Text {
            get {
                return ResourceManager.GetString("btnReset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save(F2).
        /// </summary>
        internal static string btnSave_Text {
            get {
                return ResourceManager.GetString("btnSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and New(F3).
        /// </summary>
        internal static string btnSaveAndNew_Text {
            get {
                return ResourceManager.GetString("btnSaveAndNew.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and Create New without printing (F12).
        /// </summary>
        internal static string btnSaveAndNewNoPrint_Text {
            get {
                return ResourceManager.GetString("btnSaveAndNewNoPrint.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, there&apos;s no enough quantity in the store.
        ///Available quantity : {0}.
        /// </summary>
        internal static string CheckPrdQtyMssg {
            get {
                return ResourceManager.GetString("CheckPrdQtyMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to close invoice form?.
        /// </summary>
        internal static string CloseFormMssg {
            get {
                return ResourceManager.GetString("CloseFormMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string colAccName_Caption {
            get {
                return ResourceManager.GetString("colAccName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string colAccNo_Caption {
            get {
                return ResourceManager.GetString("colAccNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number.
        /// </summary>
        internal static string colCount_Caption {
            get {
                return ResourceManager.GetString("colCount.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string colDscntAmount_Caption {
            get {
                return ResourceManager.GetString("colDscntAmount.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final total.
        /// </summary>
        internal static string colFinalAmount_Caption {
            get {
                return ResourceManager.GetString("colFinalAmount.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string colHeight_Caption {
            get {
                return ResourceManager.GetString("colHeight.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurment Unit.
        /// </summary>
        internal static string colMsur_Caption {
            get {
                return ResourceManager.GetString("colMsur.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string colprdName_Caption {
            get {
                return ResourceManager.GetString("colprdName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product No..
        /// </summary>
        internal static string colprdNo_Caption {
            get {
                return ResourceManager.GetString("colprdNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity Available.
        /// </summary>
        internal static string colprdQuanAvlb_Caption {
            get {
                return ResourceManager.GetString("colprdQuanAvlb.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string colQuanMain_Caption {
            get {
                return ResourceManager.GetString("colQuanMain.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string colsupCredit_Caption {
            get {
                return ResourceManager.GetString("colsupCredit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string colsupCurrency_Caption {
            get {
                return ResourceManager.GetString("colsupCurrency.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string colsupDebit_Caption {
            get {
                return ResourceManager.GetString("colsupDebit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string colsupDesc_Caption {
            get {
                return ResourceManager.GetString("colsupDesc.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount percentage.
        /// </summary>
        internal static string colsupDscntPercent_Caption {
            get {
                return ResourceManager.GetString("colsupDscntPercent.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string colsupPrdBarcode_Caption {
            get {
                return ResourceManager.GetString("colsupPrdBarcode.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string colsupPrdName_Caption {
            get {
                return ResourceManager.GetString("colsupPrdName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product No..
        /// </summary>
        internal static string colsupPrdNo_Caption {
            get {
                return ResourceManager.GetString("colsupPrdNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        internal static string colsupPrice_Caption {
            get {
                return ResourceManager.GetString("colsupPrice.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        internal static string colsupSalePrice_Caption {
            get {
                return ResourceManager.GetString("colsupSalePrice.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Percent.
        /// </summary>
        internal static string colsupTaxPercent_Caption {
            get {
                return ResourceManager.GetString("colsupTaxPercent.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string colTaxPrice_Caption {
            get {
                return ResourceManager.GetString("colTaxPrice.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string colWidth_Caption {
            get {
                return ResourceManager.GetString("colWidth.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, operation could not be complete, sale price excceds minimum sale price for the product.
        ///Sale price : {0}
        ///Product minimum sale price : {1}.
        /// </summary>
        internal static string ExccededPrdPriceFloarMssg {
            get {
                return ResourceManager.GetString("ExccededPrdPriceFloarMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no data in the grid!.
        /// </summary>
        internal static string GridErrorMssg {
            get {
                return ResourceManager.GetString("GridErrorMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter all group info from group form in Store Mangment..
        /// </summary>
        internal static string grpErrorMssg {
            get {
                return ResourceManager.GetString("grpErrorMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The final amount.
        /// </summary>
        internal static string ItemForAmountFainal_Text {
            get {
                return ResourceManager.GetString("ItemForAmountFainal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bank.
        /// </summary>
        internal static string ItemForBankId_Text {
            get {
                return ResourceManager.GetString("ItemForBankId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode number:.
        /// </summary>
        internal static string ItemForBarcodeText_Text {
            get {
                return ResourceManager.GetString("ItemForBarcodeText.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box Name.
        /// </summary>
        internal static string ItemForBoxNo_Text {
            get {
                return ResourceManager.GetString("ItemForBoxNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Price.
        /// </summary>
        internal static string ItemForCurrencyChng_Text {
            get {
                return ResourceManager.GetString("ItemForCurrencyChng.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice date.
        /// </summary>
        internal static string ItemForDate_Text {
            get {
                return ResourceManager.GetString("ItemForDate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delivery Date.
        /// </summary>
        internal static string ItemForDeliveryDate_Text {
            get {
                return ResourceManager.GetString("ItemForDeliveryDate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string ItemFordescountAmount_Text {
            get {
                return ResourceManager.GetString("ItemFordescountAmount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Price.
        /// </summary>
        internal static string ItemFordescountCurChange_Text {
            get {
                return ResourceManager.GetString("ItemFordescountCurChange.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ItemFordescountDesc_Text {
            get {
                return ResourceManager.GetString("ItemFordescountDesc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DiscountAccount.
        /// </summary>
        internal static string ItemFordescountNo_Text {
            get {
                return ResourceManager.GetString("ItemFordescountNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field Number.
        /// </summary>
        internal static string ItemForFieldNumber_Text {
            get {
                return ResourceManager.GetString("ItemForFieldNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type.
        /// </summary>
        internal static string ItemForIsCash_Text {
            get {
                return ResourceManager.GetString("ItemForIsCash.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string ItemFornotDate_Text {
            get {
                return ResourceManager.GetString("ItemFornotDate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes.
        /// </summary>
        internal static string ItemForNotes_Text {
            get {
                return ResourceManager.GetString("ItemForNotes.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Cash :.
        /// </summary>
        internal static string itemForPaidCash_Text {
            get {
                return ResourceManager.GetString("itemForPaidCash.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Credit Card.
        /// </summary>
        internal static string itemForPaidCreditCard_Text {
            get {
                return ResourceManager.GetString("itemForPaidCreditCard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Team.
        /// </summary>
        internal static string ItemForPaymentTeam_Text {
            get {
                return ResourceManager.GetString("ItemForPaymentTeam.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Frome.
        /// </summary>
        internal static string ItemForPeriodFrome_Text {
            get {
                return ResourceManager.GetString("ItemForPeriodFrome.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period To.
        /// </summary>
        internal static string ItemForPeriodTo_Text {
            get {
                return ResourceManager.GetString("ItemForPeriodTo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Order No :.
        /// </summary>
        internal static string ItemForPoNumber_Text {
            get {
                return ResourceManager.GetString("ItemForPoNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        internal static string ItemForRegistrationNumber_Text {
            get {
                return ResourceManager.GetString("ItemForRegistrationNumber.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining :.
        /// </summary>
        internal static string itemForRemaingCash_Text {
            get {
                return ResourceManager.GetString("itemForRemaingCash.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Round off the final total.
        /// </summary>
        internal static string ItemForRoundTotal_Text {
            get {
                return ResourceManager.GetString("ItemForRoundTotal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shipping Date.
        /// </summary>
        internal static string ItemForShippingDate_Text {
            get {
                return ResourceManager.GetString("ItemForShippingDate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store.
        /// </summary>
        internal static string ItemForStore_Text {
            get {
                return ResourceManager.GetString("ItemForStore.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string ItemForsupCur_Text {
            get {
                return ResourceManager.GetString("ItemForsupCur.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount percentage.
        /// </summary>
        internal static string itemForsupDscntPercent_Text {
            get {
                return ResourceManager.GetString("itemForsupDscntPercent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        internal static string ItemForsupNo_Text {
            get {
                return ResourceManager.GetString("ItemForsupNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrence No..
        /// </summary>
        internal static string ItemForsupRefNo_Text {
            get {
                return ResourceManager.GetString("ItemForsupRefNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tax Price.
        /// </summary>
        internal static string ItemForTax_Text {
            get {
                return ResourceManager.GetString("ItemForTax.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Final.
        /// </summary>
        internal static string ItemForTotalFinal_Text {
            get {
                return ResourceManager.GetString("ItemForTotalFinal.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total paid.
        /// </summary>
        internal static string ItemForTotalPaid_Text {
            get {
                return ResourceManager.GetString("ItemForTotalPaid.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining total.
        /// </summary>
        internal static string ItemForTotalRemain_Text {
            get {
                return ResourceManager.GetString("ItemForTotalRemain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string labelDiscountString_Text {
            get {
                return ResourceManager.GetString("labelDiscountString.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count : 0.
        /// </summary>
        internal static string labelItemsCount_Text {
            get {
                return ResourceManager.GetString("labelItemsCount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Percent 5%.
        /// </summary>
        internal static string labelTaxPercent_Text {
            get {
                return ResourceManager.GetString("labelTaxPercent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tax.
        /// </summary>
        internal static string labelTaxTotalString_Text {
            get {
                return ResourceManager.GetString("labelTaxTotalString.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total price.
        /// </summary>
        internal static string labelTotalPriceString_Text {
            get {
                return ResourceManager.GetString("labelTotalPriceString.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total After Discount.
        /// </summary>
        internal static string labelTotalString_Text {
            get {
                return ResourceManager.GetString("labelTotalString.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total tax.
        /// </summary>
        internal static string labelTotalTaxString_Text {
            get {
                return ResourceManager.GetString("labelTotalTaxString.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Data.
        /// </summary>
        internal static string layoutControlCarData_Text {
            get {
                return ResourceManager.GetString("layoutControlCarData.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main data.
        /// </summary>
        internal static string layoutControlGrooupMain_Text {
            get {
                return ResourceManager.GetString("layoutControlGrooupMain.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Detail.
        /// </summary>
        internal static string layoutControlGroup10_Text {
            get {
                return ResourceManager.GetString("layoutControlGroup10.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount Info.
        /// </summary>
        internal static string layoutControlGroupDiscount_Text {
            get {
                return ResourceManager.GetString("layoutControlGroupDiscount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Data.
        /// </summary>
        internal static string layoutControlGroupPayCard_Text {
            get {
                return ResourceManager.GetString("layoutControlGroupPayCard.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count : .
        /// </summary>
        internal static string prdCount {
            get {
                return ResourceManager.GetString("prdCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, product not found..
        /// </summary>
        internal static string PrdNoFoundMssg {
            get {
                return ResourceManager.GetString("PrdNoFoundMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product price :.
        /// </summary>
        internal static string PrdPrice {
            get {
                return ResourceManager.GetString("PrdPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to print invoice?.
        /// </summary>
        internal static string printInvoiceMssg {
            get {
                return ResourceManager.GetString("printInvoiceMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required filed!..
        /// </summary>
        internal static string requiredField {
            get {
                return ResourceManager.GetString("requiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, sale invoice no. {0} have been used..
        /// </summary>
        internal static string saleErrMssg {
            get {
                return ResourceManager.GetString("saleErrMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, sale return invoice no. {0} have been used..
        /// </summary>
        internal static string saleRtrnErrMssg {
            get {
                return ResourceManager.GetString("saleRtrnErrMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select checked rows first..
        /// </summary>
        internal static string saleRtrnMarkErrMssg {
            get {
                return ResourceManager.GetString("saleRtrnMarkErrMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale return invoice no. {0}.
        /// </summary>
        internal static string saleRtrnSuccessMssg {
            get {
                return ResourceManager.GetString("saleRtrnSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale invoice no. {0}.
        /// </summary>
        internal static string saleSuccessMssg {
            get {
                return ResourceManager.GetString("saleSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items search: Ctrl + F.
        /// </summary>
        internal static string simpleLabelItem1_Text {
            get {
                return ResourceManager.GetString("simpleLabelItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer No..
        /// </summary>
        internal static string supCustNo_Properties_Columns0 {
            get {
                return ResourceManager.GetString("supCustNo.Properties.Columns0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string supCustNo_Properties_Columns1 {
            get {
                return ResourceManager.GetString("supCustNo.Properties.Columns1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Invoice.
        /// </summary>
        internal static string this_Sale {
            get {
                return ResourceManager.GetString("this.Sale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Return Invoice.
        /// </summary>
        internal static string this_SaleRtrn {
            get {
                return ResourceManager.GetString("this.SaleRtrn", resourceCulture);
            }
        }
    }
}
