//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class formAddAccountEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal formAddAccountEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.formAddAccountEn", typeof(formAddAccountEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assets.
        /// </summary>
        internal static string accCatComboBoxEdit_Properties_Items {
            get {
                return ResourceManager.GetString("accCatComboBoxEdit.Properties.Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liabilities.
        /// </summary>
        internal static string accCatComboBoxEdit_Properties_Items3 {
            get {
                return ResourceManager.GetString("accCatComboBoxEdit.Properties.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string accCatComboBoxEdit_Properties_Items6 {
            get {
                return ResourceManager.GetString("accCatComboBoxEdit.Properties.Items6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revenue.
        /// </summary>
        internal static string accCatComboBoxEdit_Properties_Items9 {
            get {
                return ResourceManager.GetString("accCatComboBoxEdit.Properties.Items9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currencies.
        /// </summary>
        internal static string accCurrencyTextEdit_Properties_Columns1 {
            get {
                return ResourceManager.GetString("accCurrencyTextEdit.Properties.Columns1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string accParentTextEdit_Properties_Columns1 {
            get {
                return ResourceManager.GetString("accParentTextEdit.Properties.Columns1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string accParentTextEdit_Properties_Columns3 {
            get {
                return ResourceManager.GetString("accParentTextEdit.Properties.Columns3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string accTypeRadioGroup_Properties_Items1 {
            get {
                return ResourceManager.GetString("accTypeRadioGroup.Properties.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub.
        /// </summary>
        internal static string accTypeRadioGroup_Properties_Items3 {
            get {
                return ResourceManager.GetString("accTypeRadioGroup.Properties.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Category.
        /// </summary>
        internal static string ItemForaccCat_Text {
            get {
                return ResourceManager.GetString("ItemForaccCat.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string ItemForaccCurrency_Text {
            get {
                return ResourceManager.GetString("ItemForaccCurrency.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        internal static string ItemForaccLevel_Text {
            get {
                return ResourceManager.GetString("ItemForaccLevel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string ItemForaccName_Text {
            get {
                return ResourceManager.GetString("ItemForaccName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string ItemForaccNo_Text {
            get {
                return ResourceManager.GetString("ItemForaccNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Account.
        /// </summary>
        internal static string ItemForaccParent_Text {
            get {
                return ResourceManager.GetString("ItemForaccParent.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Type.
        /// </summary>
        internal static string ItemForaccType_Text {
            get {
                return ResourceManager.GetString("ItemForaccType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Main Info.
        /// </summary>
        internal static string layoutGrpAccMainInfo_Text {
            get {
                return ResourceManager.GetString("layoutGrpAccMainInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Sub Info.
        /// </summary>
        internal static string layoutGrpAccSubInfo_Text {
            get {
                return ResourceManager.GetString("layoutGrpAccSubInfo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Account.
        /// </summary>
        internal static string this_Text {
            get {
                return ResourceManager.GetString("this.Text", resourceCulture);
            }
        }
    }
}
