//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class formAddProductEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal formAddProductEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.formAddProductEn", typeof(formAddProductEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, barcode no. {0} already been used!.
        /// </summary>
        internal static string BarcodeNoFoundMssg {
            get {
                return ResourceManager.GetString("BarcodeNoFoundMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale price + tax : .
        /// </summary>
        internal static string bsiSalTaxPriceString_Caption {
            get {
                return ResourceManager.GetString("bsiSalTaxPriceString.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnClose_Text {
            get {
                return ResourceManager.GetString("btnClose.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string btnDelete_Text {
            get {
                return ResourceManager.GetString("btnDelete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save(F4).
        /// </summary>
        internal static string btnSave_Text {
            get {
                return ResourceManager.GetString("btnSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Close.
        /// </summary>
        internal static string btnSaveAndClose_Text {
            get {
                return ResourceManager.GetString("btnSaveAndClose.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and New(F3).
        /// </summary>
        internal static string btnSaveAndNew_Text {
            get {
                return ResourceManager.GetString("btnSaveAndNew.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save And Print.
        /// </summary>
        internal static string btnSaveAndPrint_Text {
            get {
                return ResourceManager.GetString("btnSaveAndPrint.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Product.
        /// </summary>
        internal static string checkEdit1_Text {
            get {
                return ResourceManager.GetString("checkEdit1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Name.
        /// </summary>
        internal static string colGrpName {
            get {
                return ResourceManager.GetString("colGrpName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group No..
        /// </summary>
        internal static string colGrpNo {
            get {
                return ResourceManager.GetString("colGrpNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter this field!.
        /// </summary>
        internal static string fieldErrMssg {
            get {
                return ResourceManager.GetString("fieldErrMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string ItemForBarcode1_Text {
            get {
                return ResourceManager.GetString("ItemForBarcode1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string ItemForBarcode2_Text {
            get {
                return ResourceManager.GetString("ItemForBarcode2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string ItemForBarcode3_Text {
            get {
                return ResourceManager.GetString("ItemForBarcode3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string ItemForppmBarcode_Text {
            get {
                return ResourceManager.GetString("ItemForppmBarcode.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string ItemForppmBarcode1_Text {
            get {
                return ResourceManager.GetString("ItemForppmBarcode1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string ItemForppmBarcode2_Text {
            get {
                return ResourceManager.GetString("ItemForppmBarcode2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Price.
        /// </summary>
        internal static string ItemForppmBatchPrice_Text {
            get {
                return ResourceManager.GetString("ItemForppmBatchPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Price.
        /// </summary>
        internal static string ItemForppmBatchPrice1 {
            get {
                return ResourceManager.GetString("ItemForppmBatchPrice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Price.
        /// </summary>
        internal static string ItemForppmBatchPrice1_Text {
            get {
                return ResourceManager.GetString("ItemForppmBatchPrice1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Price.
        /// </summary>
        internal static string ItemForppmBatchPrice2 {
            get {
                return ResourceManager.GetString("ItemForppmBatchPrice2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Price.
        /// </summary>
        internal static string ItemForppmBatchPrice2_Text {
            get {
                return ResourceManager.GetString("ItemForppmBatchPrice2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Factor.
        /// </summary>
        internal static string ItemForppmConversion0_Text {
            get {
                return ResourceManager.GetString("ItemForppmConversion0.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Rate.
        /// </summary>
        internal static string ItemForppmConversion1_Text {
            get {
                return ResourceManager.GetString("ItemForppmConversion1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conversion Rate.
        /// </summary>
        internal static string ItemForppmConversion2_Text {
            get {
                return ResourceManager.GetString("ItemForppmConversion2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Sale Price.
        /// </summary>
        internal static string ItemForppmMinSalePrice_Text {
            get {
                return ResourceManager.GetString("ItemForppmMinSalePrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Sale Price.
        /// </summary>
        internal static string ItemForppmMinSalePrice1_Text {
            get {
                return ResourceManager.GetString("ItemForppmMinSalePrice1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Sale Price.
        /// </summary>
        internal static string ItemForppmMinSalePrice2_Text {
            get {
                return ResourceManager.GetString("ItemForppmMinSalePrice2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurment Unit.
        /// </summary>
        internal static string ItemForppmMsurName_Text {
            get {
                return ResourceManager.GetString("ItemForppmMsurName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurment Unit.
        /// </summary>
        internal static string ItemForppmMsurName1_Text {
            get {
                return ResourceManager.GetString("ItemForppmMsurName1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurment Unit.
        /// </summary>
        internal static string ItemForppmMsurName2_Text {
            get {
                return ResourceManager.GetString("ItemForppmMsurName2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        internal static string ItemForppmPrice_Text {
            get {
                return ResourceManager.GetString("ItemForppmPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        internal static string ItemForppmPrice1_Text {
            get {
                return ResourceManager.GetString("ItemForppmPrice1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase Price.
        /// </summary>
        internal static string ItemForppmPrice2_Text {
            get {
                return ResourceManager.GetString("ItemForppmPrice2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Price.
        /// </summary>
        internal static string ItemForppmRetailPrice_Text {
            get {
                return ResourceManager.GetString("ItemForppmRetailPrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Price.
        /// </summary>
        internal static string ItemForppmRetailPrice1_Text {
            get {
                return ResourceManager.GetString("ItemForppmRetailPrice1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retail Price.
        /// </summary>
        internal static string ItemForppmRetailPrice2_Text {
            get {
                return ResourceManager.GetString("ItemForppmRetailPrice2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        internal static string ItemForppmSalePrice_Text {
            get {
                return ResourceManager.GetString("ItemForppmSalePrice.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        internal static string ItemForppmSalePrice1_Text {
            get {
                return ResourceManager.GetString("ItemForppmSalePrice1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale Price.
        /// </summary>
        internal static string ItemForppmSalePrice2_Text {
            get {
                return ResourceManager.GetString("ItemForppmSalePrice2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specifications.
        /// </summary>
        internal static string ItemForprdDesc_Text {
            get {
                return ResourceManager.GetString("ItemForprdDesc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group No..
        /// </summary>
        internal static string ItemForprdGrpNo_Text {
            get {
                return ResourceManager.GetString("ItemForprdGrpNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Name.
        /// </summary>
        internal static string ItemForprdName_Text {
            get {
                return ResourceManager.GetString("ItemForprdName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Name.
        /// </summary>
        internal static string ItemForprdNameEng_Text {
            get {
                return ResourceManager.GetString("ItemForprdNameEng.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product No..
        /// </summary>
        internal static string ItemForprdNo_Text {
            get {
                return ResourceManager.GetString("ItemForprdNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string ItemForprdQuantity_Text {
            get {
                return ResourceManager.GetString("ItemForprdQuantity.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of product.
        /// </summary>
        internal static string ItemForprdStatus {
            get {
                return ResourceManager.GetString("ItemForprdStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To store.
        /// </summary>
        internal static string ItemForprdStrId_Text {
            get {
                return ResourceManager.GetString("ItemForprdStrId.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product Main Info.
        /// </summary>
        internal static string layoutControlGroup3_Text {
            get {
                return ResourceManager.GetString("layoutControlGroup3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Quantity.
        /// </summary>
        internal static string layoutControlGroup5_Text {
            get {
                return ResourceManager.GetString("layoutControlGroup5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price and Measurment Info.
        /// </summary>
        internal static string layoutControlGroup9_Text {
            get {
                return ResourceManager.GetString("layoutControlGroup9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit 1.
        /// </summary>
        internal static string layoutControlGroupPPM1 {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string layoutControlGroupPPM1_CustomHeaderButtons {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM1.CustomHeaderButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit 1.
        /// </summary>
        internal static string layoutControlGroupPPM1_Text {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string layoutControlGroupPPM2_CustomHeaderButtons {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM2.CustomHeaderButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string layoutControlGroupPPM2_CustomHeaderButtons12 {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM2.CustomHeaderButtons12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string layoutControlGroupPPM2_CustomHeaderButtons24 {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM2.CustomHeaderButtons24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units 2.
        /// </summary>
        internal static string layoutControlGroupPPM2_Text {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Units 2.
        /// </summary>
        internal static string layoutControlGroupPPM2Main {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM2Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string layoutControlGroupPPM3_CustomHeaderButtons {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM3.CustomHeaderButtons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string layoutControlGroupPPM3_CustomHeaderButtons12 {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM3.CustomHeaderButtons12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string layoutControlGroupPPM3_CustomHeaderButtons24 {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM3.CustomHeaderButtons24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit 3.
        /// </summary>
        internal static string layoutControlGroupPPM3_Text {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unit 3.
        /// </summary>
        internal static string layoutControlGroupPPM3Main {
            get {
                return ResourceManager.GetString("layoutControlGroupPPM3Main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The store.
        /// </summary>
        internal static string layoutControlGroupStore {
            get {
                return ResourceManager.GetString("layoutControlGroupStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demand limit.
        /// </summary>
        internal static string layoutControlItem2 {
            get {
                return ResourceManager.GetString("layoutControlItem2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The highest rate.
        /// </summary>
        internal static string layoutControlItem3 {
            get {
                return ResourceManager.GetString("layoutControlItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string mainRibbonPage_Text {
            get {
                return ResourceManager.GetString("mainRibbonPage.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        internal static string mainRibbonPageGroup {
            get {
                return ResourceManager.GetString("mainRibbonPageGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter product measurment 2 first!.
        /// </summary>
        internal static string PPM2ErrMssg {
            get {
                return ResourceManager.GetString("PPM2ErrMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ppmDefaultCheckEdit {
            get {
                return ResourceManager.GetString("ppmDefaultCheckEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ppmDefaultCheckEdit2 {
            get {
                return ResourceManager.GetString("ppmDefaultCheckEdit2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        internal static string ppmDefaultCheckEdit3 {
            get {
                return ResourceManager.GetString("ppmDefaultCheckEdit3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The sales price includes tax.
        /// </summary>
        internal static string prdPriceTaxCheckEdit {
            get {
                return ResourceManager.GetString("prdPriceTaxCheckEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purchase without tax.
        /// </summary>
        internal static string prdPurchaseTaxCheckEdit {
            get {
                return ResourceManager.GetString("prdPurchaseTaxCheckEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sale without tax.
        /// </summary>
        internal static string prdSaleTaxCheckEdit {
            get {
                return ResourceManager.GetString("prdSaleTaxCheckEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product .
        /// </summary>
        internal static string prdSuccessMssg {
            get {
                return ResourceManager.GetString("prdSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Barcode.
        /// </summary>
        internal static string simpleLabelItem1_Text {
            get {
                return ResourceManager.GetString("simpleLabelItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to product Stoped.
        /// </summary>
        internal static string SuspendedCheckEdit {
            get {
                return ResourceManager.GetString("SuspendedCheckEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Product.
        /// </summary>
        internal static string this_Text {
            get {
                return ResourceManager.GetString("this.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode No..
        /// </summary>
        internal static string toolStripLabel1_Text {
            get {
                return ResourceManager.GetString("toolStripLabel1.Text", resourceCulture);
            }
        }
    }
}
