//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Form1Ar {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Form1Ar() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.Form1Ar", typeof(Form1Ar).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متاكد من إغلاق النظام؟.
        /// </summary>
        internal static string ApplicationCloseMssg {
            get {
                return ResourceManager.GetString("ApplicationCloseMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدليل المحسابي.
        /// </summary>
        internal static string barButtonItemAccount_Caption {
            get {
                return ResourceManager.GetString("barButtonItemAccount.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الأرصدة الإفتتاحية.
        /// </summary>
        internal static string barButtonItemAccountOpening_Caption {
            get {
                return ResourceManager.GetString("barButtonItemAccountOpening.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أرصدة الحسابات.
        /// </summary>
        internal static string barButtonItemAccountsBalance_Caption {
            get {
                return ResourceManager.GetString("barButtonItemAccountsBalance.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to النوك.
        /// </summary>
        internal static string barButtonItemBank_Caption {
            get {
                return ResourceManager.GetString("barButtonItemBank.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الصناديق.
        /// </summary>
        internal static string barButtonItemBox_Caption {
            get {
                return ResourceManager.GetString("barButtonItemBox.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفروع.
        /// </summary>
        internal static string barButtonItemBranches_Caption {
            get {
                return ResourceManager.GetString("barButtonItemBranches.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوحة التحكم.
        /// </summary>
        internal static string barButtonItemControlPanel_Caption {
            get {
                return ResourceManager.GetString("barButtonItemControlPanel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملات.
        /// </summary>
        internal static string barButtonItemCurrency_Caption {
            get {
                return ResourceManager.GetString("barButtonItemCurrency.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العملاء.
        /// </summary>
        internal static string barButtonItemCustomer_Caption {
            get {
                return ResourceManager.GetString("barButtonItemCustomer.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموظفين.
        /// </summary>
        internal static string barButtonItemEmployee_Caption {
            get {
                return ResourceManager.GetString("barButtonItemEmployee.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صرف مرتبات الموظفين.
        /// </summary>
        internal static string barButtonItemEmployeeVocher_Caption {
            get {
                return ResourceManager.GetString("barButtonItemEmployeeVocher.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيود اليومية.
        /// </summary>
        internal static string barButtonItemEntry_Caption {
            get {
                return ResourceManager.GetString("barButtonItemEntry.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الحركة اليومية.
        /// </summary>
        internal static string barButtonItemEntryAll_Caption {
            get {
                return ResourceManager.GetString("barButtonItemEntryAll.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سندات القبض.
        /// </summary>
        internal static string barButtonItemEntryRecipt_Caption {
            get {
                return ResourceManager.GetString("barButtonItemEntryRecipt.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيود المرحلة.
        /// </summary>
        internal static string barButtonItemEntryTarhel_Caption {
            get {
                return ResourceManager.GetString("barButtonItemEntryTarhel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سندات الصرف.
        /// </summary>
        internal static string barButtonItemEntryVocher_Caption {
            get {
                return ResourceManager.GetString("barButtonItemEntryVocher.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حركة الأصناف.
        /// </summary>
        internal static string barButtonItemProductQuantity_Caption {
            get {
                return ResourceManager.GetString("barButtonItemProductQuantity.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المشتريات.
        /// </summary>
        internal static string barButtonItemPurchase_Caption {
            get {
                return ResourceManager.GetString("barButtonItemPurchase.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير المشتريات المرحلة.
        /// </summary>
        internal static string barButtonItemPurchaseAll_Caption {
            get {
                return ResourceManager.GetString("barButtonItemPurchaseAll.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير المشتريات المحذوفه.
        /// </summary>
        internal static string barButtonItemPurchaseDel_Caption {
            get {
                return ResourceManager.GetString("barButtonItemPurchaseDel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مردود المشتريات.
        /// </summary>
        internal static string barButtonItemPurchaseRtrn_Caption {
            get {
                return ResourceManager.GetString("barButtonItemPurchaseRtrn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير مردود المشتريات المحذوفه.
        /// </summary>
        internal static string barButtonItemPurchaseRtrnDel_Caption {
            get {
                return ResourceManager.GetString("barButtonItemPurchaseRtrnDel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المبيعات.
        /// </summary>
        internal static string barButtonItemSale_Caption {
            get {
                return ResourceManager.GetString("barButtonItemSale.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير المبيعات المرحلة.
        /// </summary>
        internal static string barButtonItemSaleAll_Caption {
            get {
                return ResourceManager.GetString("barButtonItemSaleAll.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير المبيعات المحذوفه.
        /// </summary>
        internal static string barButtonItemSaleDel_Caption {
            get {
                return ResourceManager.GetString("barButtonItemSaleDel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير عرض الأسعار.
        /// </summary>
        internal static string barButtonItemSalePriceOffer_Caption {
            get {
                return ResourceManager.GetString("barButtonItemSalePriceOffer.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مردود المبيعات.
        /// </summary>
        internal static string barButtonItemSaleRtrn_Caption {
            get {
                return ResourceManager.GetString("barButtonItemSaleRtrn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فواتير مردود المبيعات المحذوفه.
        /// </summary>
        internal static string barButtonItemSaleRtrnDel_Caption {
            get {
                return ResourceManager.GetString("barButtonItemSaleRtrnDel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المخازن.
        /// </summary>
        internal static string barButtonItemStore_Caption {
            get {
                return ResourceManager.GetString("barButtonItemStore.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الموردين.
        /// </summary>
        internal static string barButtonItemSupplier_Caption {
            get {
                return ResourceManager.GetString("barButtonItemSupplier.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة الضريبية.
        /// </summary>
        internal static string barButtonItemTaxDeclaration_Caption {
            get {
                return ResourceManager.GetString("barButtonItemTaxDeclaration.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المستخمين.
        /// </summary>
        internal static string barButtonItemUserRIght_Caption {
            get {
                return ResourceManager.GetString("barButtonItemUserRIght.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التحويل المخزني.
        /// </summary>
        internal static string bbiStockTrans_Caption {
            get {
                return ResourceManager.GetString("bbiStockTrans.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخزين الاصناف.
        /// </summary>
        internal static string bbiStoreProducts_Caption {
            get {
                return ResourceManager.GetString("bbiStoreProducts.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بيانات الأصناف التفصيلية.
        /// </summary>
        internal static string bbiStoreProductsData_Caption {
            get {
                return ResourceManager.GetString("bbiStoreProductsData.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة جديد(F2).
        /// </summary>
        internal static string btnAddNew_Text {
            get {
                return ResourceManager.GetString("btnAddNew.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اغلاق.
        /// </summary>
        internal static string btnClose_Text {
            get {
                return ResourceManager.GetString("btnClose.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف(F6).
        /// </summary>
        internal static string btnDelete_Text {
            get {
                return ResourceManager.GetString("btnDelete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة(F7).
        /// </summary>
        internal static string btnPrint_Text {
            get {
                return ResourceManager.GetString("btnPrint.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحديث(F5).
        /// </summary>
        internal static string btnRefresh_Text {
            get {
                return ResourceManager.GetString("btnRefresh.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعادة التهيئة(F5).
        /// </summary>
        internal static string btnReset_Text {
            get {
                return ResourceManager.GetString("btnReset.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ(F3).
        /// </summary>
        internal static string btnSave_Text {
            get {
                return ResourceManager.GetString("btnSave.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل(F4).
        /// </summary>
        internal static string btnUpdate_Text {
            get {
                return ResourceManager.GetString("btnUpdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to B-Tech.
        /// </summary>
        internal static string Form1 {
            get {
                return ResourceManager.GetString("Form1", resourceCulture);
            }
        }
    }
}
