//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class formAddCurrencyEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal formAddCurrencyEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.formAddCurrencyEn", typeof(formAddCurrencyEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string curTypeRadioGroup_Properties_Items1 {
            get {
                return ResourceManager.GetString("curTypeRadioGroup.Properties.Items1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sub.
        /// </summary>
        internal static string curTypeRadioGroup_Properties_Items3 {
            get {
                return ResourceManager.GetString("curTypeRadioGroup.Properties.Items3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Celling.
        /// </summary>
        internal static string ItemForcurCelling_Text {
            get {
                return ResourceManager.GetString("ItemForcurCelling.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Price.
        /// </summary>
        internal static string ItemForcurChange_Text {
            get {
                return ResourceManager.GetString("ItemForcurChange.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floar.
        /// </summary>
        internal static string ItemForcurFloar_Text {
            get {
                return ResourceManager.GetString("ItemForcurFloar.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Name.
        /// </summary>
        internal static string ItemForcurName_Text {
            get {
                return ResourceManager.GetString("ItemForcurName.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Symbol.
        /// </summary>
        internal static string ItemForcurSign_Text {
            get {
                return ResourceManager.GetString("ItemForcurSign.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Type.
        /// </summary>
        internal static string ItemForcurType_Text {
            get {
                return ResourceManager.GetString("ItemForcurType.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency Info.
        /// </summary>
        internal static string layoutControlGroup1_Text {
            get {
                return ResourceManager.GetString("layoutControlGroup1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Currency.
        /// </summary>
        internal static string this_Text {
            get {
                return ResourceManager.GetString("this.Text", resourceCulture);
            }
        }
    }
}
