//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class formAddEntryEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal formAddEntryEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.formAddEntryEn", typeof(formAddEntryEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string barButtonItemClose_Caption {
            get {
                return ResourceManager.GetString("barButtonItemClose.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string barButtonItemSave_Caption {
            get {
                return ResourceManager.GetString("barButtonItemSave.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Tax.
        /// </summary>
        internal static string checkEditTax_Properties_Caption {
            get {
                return ResourceManager.GetString("checkEditTax.Properties.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string colentAccName_Caption {
            get {
                return ResourceManager.GetString("colentAccName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string colentAccNo_Caption {
            get {
                return ResourceManager.GetString("colentAccNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string colentCredit_Caption {
            get {
                return ResourceManager.GetString("colentCredit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Forign Currency.
        /// </summary>
        internal static string colentCreditFrgn_Caption {
            get {
                return ResourceManager.GetString("colentCreditFrgn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Price.
        /// </summary>
        internal static string colentCurChange_Caption {
            get {
                return ResourceManager.GetString("colentCurChange.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string colentCurrncy_Caption {
            get {
                return ResourceManager.GetString("colentCurrncy.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string colentCusName_Caption {
            get {
                return ResourceManager.GetString("colentCusName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer No..
        /// </summary>
        internal static string colentCusNo_Caption {
            get {
                return ResourceManager.GetString("colentCusNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string colentDebit_Caption {
            get {
                return ResourceManager.GetString("colentDebit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Forign Currency.
        /// </summary>
        internal static string colentDebitFrgn_Caption {
            get {
                return ResourceManager.GetString("colentDebitFrgn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string colentDesc_Caption {
            get {
                return ResourceManager.GetString("colentDesc.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Percent.
        /// </summary>
        internal static string colentTaxPercent_Caption {
            get {
                return ResourceManager.GetString("colentTaxPercent.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Amount.
        /// </summary>
        internal static string colentTaxPrice_Caption {
            get {
                return ResourceManager.GetString("colentTaxPrice.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, entey no. {0} have been used..
        /// </summary>
        internal static string entErrorMssg {
            get {
                return ResourceManager.GetString("entErrorMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily entry no. {0}.
        /// </summary>
        internal static string entSuccessMssg {
            get {
                return ResourceManager.GetString("entSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string ItemForentAmount_Text {
            get {
                return ResourceManager.GetString("ItemForentAmount.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ItemForentDate_Text {
            get {
                return ResourceManager.GetString("ItemForentDate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string ItemForentDesc_Text {
            get {
                return ResourceManager.GetString("ItemForentDesc.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry No..
        /// </summary>
        internal static string ItemForentNo_Text {
            get {
                return ResourceManager.GetString("ItemForentNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrence No..
        /// </summary>
        internal static string ItemForentRefNo_Text {
            get {
                return ResourceManager.GetString("ItemForentRefNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Main Info.
        /// </summary>
        internal static string layoutControlGroup4_Text {
            get {
                return ResourceManager.GetString("layoutControlGroup4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string ribbonPage1_Text {
            get {
                return ResourceManager.GetString("ribbonPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ribbonPageGroup1_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter valid amounts..
        /// </summary>
        internal static string validateAmountMssg {
            get {
                return ResourceManager.GetString("validateAmountMssg", resourceCulture);
            }
        }
    }
}
