//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace accounting_1._0.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ReportAccountBillEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ReportAccountBillEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("accounting_1._0.Language.ReportAccountBillEn", typeof(ReportAccountBillEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string parameter1_Description {
            get {
                return ResourceManager.GetString("parameter1.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Date.
        /// </summary>
        internal static string parameter2_Description {
            get {
                return ResourceManager.GetString("parameter2.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Date.
        /// </summary>
        internal static string parameter3_Description {
            get {
                return ResourceManager.GetString("parameter3.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening Balance:.
        /// </summary>
        internal static string xrLabel11_Text {
            get {
                return ResourceManager.GetString("xrLabel11.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining Balance.
        /// </summary>
        internal static string xrLabel12_Text {
            get {
                return ResourceManager.GetString("xrLabel12.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Balance Report.
        /// </summary>
        internal static string xrLabel15_Text {
            get {
                return ResourceManager.GetString("xrLabel15.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From : [Parameters.parameterDateStart!yyyy/MM/dd] To : [Parameters.parameterDateEnd!yyyy/MM/dd].
        /// </summary>
        internal static string xrLabel2_Text {
            get {
                return ResourceManager.GetString("xrLabel2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كشف حساب.
        /// </summary>
        internal static string xrLabel5_Text {
            get {
                return ResourceManager.GetString("xrLabel5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No. : [accNo].
        /// </summary>
        internal static string xrLabel7_Text {
            get {
                return ResourceManager.GetString("xrLabel7.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total:.
        /// </summary>
        internal static string xrLabel8_Text {
            get {
                return ResourceManager.GetString("xrLabel8.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency: [currencyName].
        /// </summary>
        internal static string xrLabel9_Text {
            get {
                return ResourceManager.GetString("xrLabel9.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No.
        /// </summary>
        internal static string xrTableCell1_Text {
            get {
                return ResourceManager.GetString("xrTableCell1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type.
        /// </summary>
        internal static string xrTableCell2_Text {
            get {
                return ResourceManager.GetString("xrTableCell2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string xrTableCell3_Text {
            get {
                return ResourceManager.GetString("xrTableCell3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string xrTableCell4_Text {
            get {
                return ResourceManager.GetString("xrTableCell4.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string xrTableCell5_Text {
            get {
                return ResourceManager.GetString("xrTableCell5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string xrTableCell6_Text {
            get {
                return ResourceManager.GetString("xrTableCell6.Text", resourceCulture);
            }
        }
    }
}
