//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SalesManagementAr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SalesManagementAr() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.SalesManagementAr", typeof(SalesManagementAr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا لا يتوفر لديك الكميه المطلوبه في المخزن.
        ///الكمية المتوفرة : {0}.
        /// </summary>
        internal static string CheckPrdQtyMssg {
            get {
                return ResourceManager.GetString("CheckPrdQtyMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل أنت متاكد من إغلاق الفاتورة؟.
        /// </summary>
        internal static string CloseFormMssg {
            get {
                return ResourceManager.GetString("CloseFormMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد : .
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من حذف فاتورة المبيعات  رقم : {0}؟.
        /// </summary>
        internal static string delSaleMssg {
            get {
                return ResourceManager.GetString("delSaleMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من حذف فاتورة مردود المبيعات رقم : {0}؟.
        /// </summary>
        internal static string delSaleRtrnMssg {
            get {
                return ResourceManager.GetString("delSaleRtrnMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف فاتورة مردود المبيعات رقم : {0} بنجاح..
        /// </summary>
        internal static string delSaleRtrnSuccessMssg {
            get {
                return ResourceManager.GetString("delSaleRtrnSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف فاتورة المبيعات رقم : {0} بنجاح..
        /// </summary>
        internal static string delSaleSuccessMssg {
            get {
                return ResourceManager.GetString("delSaleSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا سعر البيع اقل من الحد الادنى لسعر بيع الصنف.
        ///سعر البيع : {0}
        ///الحد الأدنى لسعر بيع الصنف : {1}.
        /// </summary>
        internal static string ExccededPrdPriceFloarMssg {
            get {
                return ResourceManager.GetString("ExccededPrdPriceFloarMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا، لا يوجد بيانات في الجدول!.
        /// </summary>
        internal static string GridErrorMssg {
            get {
                return ResourceManager.GetString("GridErrorMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا يجب إدخال جميع بيانات المجموعة من شاشة المجموعات في إدارة المخازن..
        /// </summary>
        internal static string grpErrorMssg {
            get {
                return ResourceManager.GetString("grpErrorMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من ترحيل الفوانير؟.
        /// </summary>
        internal static string phaseMssg {
            get {
                return ResourceManager.GetString("phaseMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم ترحيل الفواتير بنجاح..
        /// </summary>
        internal static string phaseSuccessMssg {
            get {
                return ResourceManager.GetString("phaseSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأصناف : .
        /// </summary>
        internal static string prdCount {
            get {
                return ResourceManager.GetString("prdCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا لم يتم العثور على الصنف المطلوب..
        /// </summary>
        internal static string PrdNoFoundMssg {
            get {
                return ResourceManager.GetString("PrdNoFoundMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سعر شراء الصنف :.
        /// </summary>
        internal static string PrdPrice {
            get {
                return ResourceManager.GetString("PrdPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد طباعة السند؟.
        /// </summary>
        internal static string printInvoiceMssg {
            get {
                return ResourceManager.GetString("printInvoiceMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد طباعة الفاتورة رقم : {0}؟.
        /// </summary>
        internal static string printMssg {
            get {
                return ResourceManager.GetString("printMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال هذا الحقل.
        /// </summary>
        internal static string requiredField {
            get {
                return ResourceManager.GetString("requiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا رقم فاتورة المبيعات : {0} قد تم إستخدامه مسبقا!.
        /// </summary>
        internal static string saleErrMssg {
            get {
                return ResourceManager.GetString("saleErrMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عذرا رقم فاتورة مردود المبيعات : {0} قد تم إستخدامه مسبقا!.
        /// </summary>
        internal static string saleRtrnErrMssg {
            get {
                return ResourceManager.GetString("saleRtrnErrMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب تحديد الصفوف في الجدول اولا..
        /// </summary>
        internal static string saleRtrnMarkErrMssg {
            get {
                return ResourceManager.GetString("saleRtrnMarkErrMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة مردود المبيعات رقم : {0}.
        /// </summary>
        internal static string saleRtrnSuccessMssg {
            get {
                return ResourceManager.GetString("saleRtrnSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فاتورة المبيعات رقم : {0}.
        /// </summary>
        internal static string saleSuccessMssg {
            get {
                return ResourceManager.GetString("saleSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من إلغاء الترحيل الفاتورة رقم : {0}؟.
        /// </summary>
        internal static string undoPhaseMssg {
            get {
                return ResourceManager.GetString("undoPhaseMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إلغاء ترحيل الفاتورة رقم : {0} بنجاح..
        /// </summary>
        internal static string undoPhaseSuccesMssg {
            get {
                return ResourceManager.GetString("undoPhaseSuccesMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل انت متاكد من الغاء ترحيل الفوانير؟.
        /// </summary>
        internal static string undoSelectionPhaseMssg {
            get {
                return ResourceManager.GetString("undoSelectionPhaseMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الغاء ترحيل الفواتير بنجاح..
        /// </summary>
        internal static string undoSelectionPhaseSuccessMssg {
            get {
                return ResourceManager.GetString("undoSelectionPhaseSuccessMssg", resourceCulture);
            }
        }
    }
}
