//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UCAccOpeningEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UCAccOpeningEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.UCAccOpeningEn", typeof(UCAccOpeningEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string barButtonItem1_Caption {
            get {
                return ResourceManager.GetString("barButtonItem1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string bbiDelete_Caption {
            get {
                return ResourceManager.GetString("bbiDelete.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string bbiRefresh_Caption {
            get {
                return ResourceManager.GetString("bbiRefresh.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency : .
        /// </summary>
        internal static string bsiRecordsCount_Caption {
            get {
                return ResourceManager.GetString("bsiRecordsCount.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forign Currency.
        /// </summary>
        internal static string bsiRecordsCountFrgn_Caption {
            get {
                return ResourceManager.GetString("bsiRecordsCountFrgn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string colasAccName_Caption {
            get {
                return ResourceManager.GetString("colasAccName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string colasAccName1_Caption {
            get {
                return ResourceManager.GetString("colasAccName1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string colasAccNo_Caption {
            get {
                return ResourceManager.GetString("colasAccNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string colasAccNo1_Caption {
            get {
                return ResourceManager.GetString("colasAccNo1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string colasCredit_Caption {
            get {
                return ResourceManager.GetString("colasCredit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string colasCredit1_Caption {
            get {
                return ResourceManager.GetString("colasCredit1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Forign Currency.
        /// </summary>
        internal static string colasCreditFrgn_Caption {
            get {
                return ResourceManager.GetString("colasCreditFrgn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string colasCurrency_Caption {
            get {
                return ResourceManager.GetString("colasCurrency.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Price.
        /// </summary>
        internal static string colasCurrencyChng_Caption {
            get {
                return ResourceManager.GetString("colasCurrencyChng.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string colasDate_Caption {
            get {
                return ResourceManager.GetString("colasDate.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string colasDate1_Caption {
            get {
                return ResourceManager.GetString("colasDate1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string colasDebit_Caption {
            get {
                return ResourceManager.GetString("colasDebit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string colasDebit1_Caption {
            get {
                return ResourceManager.GetString("colasDebit1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Forign Currency.
        /// </summary>
        internal static string colasDebitFrgn_Caption {
            get {
                return ResourceManager.GetString("colasDebitFrgn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string colasTotal_Caption {
            get {
                return ResourceManager.GetString("colasTotal.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string colempId_Caption {
            get {
                return ResourceManager.GetString("colempId.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string ItemForasAccNo_Text {
            get {
                return ResourceManager.GetString("ItemForasAccNo.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string ItemForasCreditFrgn_Text {
            get {
                return ResourceManager.GetString("ItemForasCreditFrgn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange Price.
        /// </summary>
        internal static string ItemForasCurrencyChng_Text {
            get {
                return ResourceManager.GetString("ItemForasCurrencyChng.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string ItemForasDebitFrgn_Text {
            get {
                return ResourceManager.GetString("ItemForasDebitFrgn.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposite Accounts Local Currency.
        /// </summary>
        internal static string layoutControlGroup2_Text {
            get {
                return ResourceManager.GetString("layoutControlGroup2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deposite Accounts Forign Currency.
        /// </summary>
        internal static string layoutControlGroup5_Text {
            get {
                return ResourceManager.GetString("layoutControlGroup5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string layoutControlItem1_Text {
            get {
                return ResourceManager.GetString("layoutControlItem1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string layoutControlItem2_Text {
            get {
                return ResourceManager.GetString("layoutControlItem2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string layoutControlItem3_Text {
            get {
                return ResourceManager.GetString("layoutControlItem3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string ribbonPage1_Text {
            get {
                return ResourceManager.GetString("ribbonPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local Currency.
        /// </summary>
        internal static string ribbonPageGroup1_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ribbonPageGroup2_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forign Currency.
        /// </summary>
        internal static string ribbonPageGroup3_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup3.Text", resourceCulture);
            }
        }
    }
}
