//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UCcustomersEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UCcustomersEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.UCcustomersEn", typeof(UCcustomersEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///F6.
        /// </summary>
        internal static string bbiDelete_Caption {
            get {
                return ResourceManager.GetString("bbiDelete.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///F3.
        /// </summary>
        internal static string bbiEdit_Caption {
            get {
                return ResourceManager.GetString("bbiEdit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Customer
        ///F2.
        /// </summary>
        internal static string bbiNew_Caption {
            get {
                return ResourceManager.GetString("bbiNew.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print
        ///F7.
        /// </summary>
        internal static string bbiPrintPreview_Caption {
            get {
                return ResourceManager.GetString("bbiPrintPreview.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh
        ///F5.
        /// </summary>
        internal static string bbiRefresh_Caption {
            get {
                return ResourceManager.GetString("bbiRefresh.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string colcustAccName_Caption {
            get {
                return ResourceManager.GetString("colcustAccName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string colcustAccNo_Caption {
            get {
                return ResourceManager.GetString("colcustAccNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string colcustAddress_Caption {
            get {
                return ResourceManager.GetString("colcustAddress.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account celling.
        /// </summary>
        internal static string colcustCellingCredit_Caption {
            get {
                return ResourceManager.GetString("colcustCellingCredit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        internal static string colcustCity_Caption {
            get {
                return ResourceManager.GetString("colcustCity.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        internal static string colcustCountry_Caption {
            get {
                return ResourceManager.GetString("colcustCountry.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string colcustEmail_Caption {
            get {
                return ResourceManager.GetString("colcustEmail.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string colcustName_Caption {
            get {
                return ResourceManager.GetString("colcustName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer No..
        /// </summary>
        internal static string colcustNo_Caption {
            get {
                return ResourceManager.GetString("colcustNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone No..
        /// </summary>
        internal static string colcustPhnNo_Caption {
            get {
                return ResourceManager.GetString("colcustPhnNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string ribbonPage1_Text {
            get {
                return ResourceManager.GetString("ribbonPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ribbonPageGroup1_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print and Export.
        /// </summary>
        internal static string ribbonPageGroup2_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup2.Text", resourceCulture);
            }
        }
    }
}
