//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UCemployeesVchrEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UCemployeesVchrEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.UCemployeesVchrEn", typeof(UCemployeesVchrEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Hide Phased Checkbox
        ///F8.
        /// </summary>
        internal static string barButtonItem1_Caption {
            get {
                return ResourceManager.GetString("barButtonItem1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Vochers
        ///F9.
        /// </summary>
        internal static string barButtonItem2_Caption {
            get {
                return ResourceManager.GetString("barButtonItem2.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///F6.
        /// </summary>
        internal static string bbiDelete_Caption {
            get {
                return ResourceManager.GetString("bbiDelete.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///F4.
        /// </summary>
        internal static string bbiEdit_Caption {
            get {
                return ResourceManager.GetString("bbiEdit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Employee Voucher
        ///F2.
        /// </summary>
        internal static string bbiNew_Caption {
            get {
                return ResourceManager.GetString("bbiNew.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print
        ///F7.
        /// </summary>
        internal static string bbiPrintPreview_Caption {
            get {
                return ResourceManager.GetString("bbiPrintPreview.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh
        ///F5.
        /// </summary>
        internal static string bbiRefresh_Caption {
            get {
                return ResourceManager.GetString("bbiRefresh.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string colentAccName1_Caption {
            get {
                return ResourceManager.GetString("colentAccName1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string colentAccNo1_Caption {
            get {
                return ResourceManager.GetString("colentAccNo1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string colentAmount_Caption {
            get {
                return ResourceManager.GetString("colentAmount.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box No..
        /// </summary>
        internal static string colentBoxNo_Caption {
            get {
                return ResourceManager.GetString("colentBoxNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string colentCurrency_Caption {
            get {
                return ResourceManager.GetString("colentCurrency.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string colentDate_Caption {
            get {
                return ResourceManager.GetString("colentDate.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string colentDebit1_Caption {
            get {
                return ResourceManager.GetString("colentDebit1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string colentDesc_Caption {
            get {
                return ResourceManager.GetString("colentDesc.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string colentDesc1_Caption {
            get {
                return ResourceManager.GetString("colentDesc1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vocher No..
        /// </summary>
        internal static string colentNo_Caption {
            get {
                return ResourceManager.GetString("colentNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORDS :.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete staff payroll no.{0}?.
        /// </summary>
        internal static string delEntMssg {
            get {
                return ResourceManager.GetString("delEntMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted staff payroll no.{0}.
        /// </summary>
        internal static string delEntSuccessMssg {
            get {
                return ResourceManager.GetString("delEntSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm phase staff payroll(s)?.
        /// </summary>
        internal static string phaseMssg {
            get {
                return ResourceManager.GetString("phaseMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff payroll(s) phased successfully..
        /// </summary>
        internal static string phaseSuccessMssg {
            get {
                return ResourceManager.GetString("phaseSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Invoice No.{0}?.
        /// </summary>
        internal static string printMssg {
            get {
                return ResourceManager.GetString("printMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string ribbonPage1_Text {
            get {
                return ResourceManager.GetString("ribbonPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ribbonPageGroup1_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print and Export.
        /// </summary>
        internal static string ribbonPageGroup2_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Actions.
        /// </summary>
        internal static string ribbonPageGroup3_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup3.Text", resourceCulture);
            }
        }
    }
}
