//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccountingMS.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UCentryEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UCentryEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AccountingMS.Language.UCentryEn", typeof(UCentryEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update
        ///F4.
        /// </summary>
        internal static string barButtonItem1_Caption {
            get {
                return ResourceManager.GetString("barButtonItem1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View/Hide Phase Checkbox
        ///F8.
        /// </summary>
        internal static string barButtonItem2_Caption {
            get {
                return ResourceManager.GetString("barButtonItem2.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Vocher
        ///F7.
        /// </summary>
        internal static string barButtonItem3_Caption {
            get {
                return ResourceManager.GetString("barButtonItem3.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo Phased Entry
        ///F10.
        /// </summary>
        internal static string barButtonItem4_Caption {
            get {
                return ResourceManager.GetString("barButtonItem4.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete
        ///F6.
        /// </summary>
        internal static string bbiDelete_Caption {
            get {
                return ResourceManager.GetString("bbiDelete.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Entry
        ///F2.
        /// </summary>
        internal static string bbiNew_Caption {
            get {
                return ResourceManager.GetString("bbiNew.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh
        ///F5.
        /// </summary>
        internal static string bbiRefresh_Caption {
            get {
                return ResourceManager.GetString("bbiRefresh.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase
        ///F9.
        /// </summary>
        internal static string bbiTarhel_Caption {
            get {
                return ResourceManager.GetString("bbiTarhel.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string colentAccName_Caption {
            get {
                return ResourceManager.GetString("colentAccName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account No..
        /// </summary>
        internal static string colentAccNo_Caption {
            get {
                return ResourceManager.GetString("colentAccNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string colentAmount_Caption {
            get {
                return ResourceManager.GetString("colentAmount.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit.
        /// </summary>
        internal static string colentCredit_Caption {
            get {
                return ResourceManager.GetString("colentCredit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credit Forign Currency.
        /// </summary>
        internal static string colentCreditFrgn_Caption {
            get {
                return ResourceManager.GetString("colentCreditFrgn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer Name.
        /// </summary>
        internal static string colentCusName_Caption {
            get {
                return ResourceManager.GetString("colentCusName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer No..
        /// </summary>
        internal static string colentCusNo_Caption {
            get {
                return ResourceManager.GetString("colentCusNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string colentDate_Caption {
            get {
                return ResourceManager.GetString("colentDate.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit.
        /// </summary>
        internal static string colentDebit_Caption {
            get {
                return ResourceManager.GetString("colentDebit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debit Forign Currency.
        /// </summary>
        internal static string colentDebitFrgn_Caption {
            get {
                return ResourceManager.GetString("colentDebitFrgn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string colentDesc_Caption {
            get {
                return ResourceManager.GetString("colentDesc.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string colentDesc1_Caption {
            get {
                return ResourceManager.GetString("colentDesc1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry No.
        /// </summary>
        internal static string colentNo_Caption {
            get {
                return ResourceManager.GetString("colentNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry No.
        /// </summary>
        internal static string colentNo1_Caption {
            get {
                return ResourceManager.GetString("colentNo1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrence No..
        /// </summary>
        internal static string colentRefNo_Caption {
            get {
                return ResourceManager.GetString("colentRefNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry Type.
        /// </summary>
        internal static string colentStatus_Caption {
            get {
                return ResourceManager.GetString("colentStatus.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string colentTaxPrice_Caption {
            get {
                return ResourceManager.GetString("colentTaxPrice.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tax.
        /// </summary>
        internal static string colentTotalTax_Caption {
            get {
                return ResourceManager.GetString("colentTotalTax.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string coluserId_Caption {
            get {
                return ResourceManager.GetString("coluserId.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RECORDS :.
        /// </summary>
        internal static string count {
            get {
                return ResourceManager.GetString("count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily entry.
        /// </summary>
        internal static string dailyVocher {
            get {
                return ResourceManager.GetString("dailyVocher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete daily entry no.{0}?.
        /// </summary>
        internal static string delEntMssg {
            get {
                return ResourceManager.GetString("delEntMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully deleted daily entry no.{0}.
        /// </summary>
        internal static string delEntSuccessMssg {
            get {
                return ResourceManager.GetString("delEntSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paymnet Voucher.
        /// </summary>
        internal static string paymentVocher {
            get {
                return ResourceManager.GetString("paymentVocher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm phase Entry(s)?.
        /// </summary>
        internal static string phaseMssg {
            get {
                return ResourceManager.GetString("phaseMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry(s) phased successfully..
        /// </summary>
        internal static string phaseSuccessMssg {
            get {
                return ResourceManager.GetString("phaseSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Invoice No.{0}?.
        /// </summary>
        internal static string printMssg {
            get {
                return ResourceManager.GetString("printMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReceiptVoucher.
        /// </summary>
        internal static string ReceiptVocher {
            get {
                return ResourceManager.GetString("ReceiptVocher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        internal static string ribbonPage1_Text {
            get {
                return ResourceManager.GetString("ribbonPage1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        internal static string ribbonPageGroup1_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup1.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print and Export.
        /// </summary>
        internal static string ribbonPageGroup2_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup2.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Actions.
        /// </summary>
        internal static string ribbonPageGroup3_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup3.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phase Action.
        /// </summary>
        internal static string ribbonPageGroup5_Text {
            get {
                return ResourceManager.GetString("ribbonPageGroup5.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm undo phase entry no. {0}?.
        /// </summary>
        internal static string undoPhaseMssg {
            get {
                return ResourceManager.GetString("undoPhaseMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully undo phase entry no.{0}.
        /// </summary>
        internal static string undoPhaseSuccesMssg {
            get {
                return ResourceManager.GetString("undoPhaseSuccesMssg", resourceCulture);
            }
        }
    }
}
