//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PosFinalCost.Language {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UC_MasterInvEn {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UC_MasterInvEn() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PosFinalCost.Language.UC_MasterInvEn", typeof(UC_MasterInvEn).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New(F2).
        /// </summary>
        internal static string btnAddNew_Text {
            get {
                return ResourceManager.GetString("btnAddNew.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string btnClose_Text {
            get {
                return ResourceManager.GetString("btnClose.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnDelete_Image {
            get {
                object obj = ResourceManager.GetObject("btnDelete.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete(F6).
        /// </summary>
        internal static string btnDelete_Text {
            get {
                return ResourceManager.GetString("btnDelete.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnPrint_Image {
            get {
                object obj = ResourceManager.GetObject("btnPrint.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print(F7).
        /// </summary>
        internal static string btnPrint_Text {
            get {
                return ResourceManager.GetString("btnPrint.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap btnRefresh_Image {
            get {
                object obj = ResourceManager.GetObject("btnRefresh.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh(F5).
        /// </summary>
        internal static string btnRefresh_Text {
            get {
                return ResourceManager.GetString("btnRefresh.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update(F4).
        /// </summary>
        internal static string btnUpdate_Text {
            get {
                return ResourceManager.GetString("btnUpdate.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string colCurrency_Caption {
            get {
                return ResourceManager.GetString("colCurrency.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string colDate_Caption {
            get {
                return ResourceManager.GetString("colDate.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string colDesc_Caption {
            get {
                return ResourceManager.GetString("colDesc.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string colDscntAmount_Caption {
            get {
                return ResourceManager.GetString("colDscntAmount.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Final.
        /// </summary>
        internal static string colNet_Caption {
            get {
                return ResourceManager.GetString("colNet.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice No..
        /// </summary>
        internal static string colNo_Caption {
            get {
                return ResourceManager.GetString("colNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodcut No..
        /// </summary>
        internal static string colPrdNo_Caption {
            get {
                return ResourceManager.GetString("colPrdNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refrence No..
        /// </summary>
        internal static string colRefNo_Caption {
            get {
                return ResourceManager.GetString("colRefNo.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type.
        /// </summary>
        internal static string colStatus_Caption {
            get {
                return ResourceManager.GetString("colStatus.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string colsupAccName_Caption {
            get {
                return ResourceManager.GetString("colsupAccName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Name.
        /// </summary>
        internal static string colsupAccName1_Caption {
            get {
                return ResourceManager.GetString("colsupAccName1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 1.
        /// </summary>
        internal static int colsupAccName1_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupAccName1.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string colsupCredit_Caption {
            get {
                return ResourceManager.GetString("colsupCredit.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 9.
        /// </summary>
        internal static int colsupCurrency_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupCurrency.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 10.
        /// </summary>
        internal static int colsupDate_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupDate.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 3.
        /// </summary>
        internal static int colsupDesc_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupDesc.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 7.
        /// </summary>
        internal static int colsupDscntAmount_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupDscntAmount.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurment Unit.
        /// </summary>
        internal static string colsupMsur_Caption {
            get {
                return ResourceManager.GetString("colsupMsur.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 0.
        /// </summary>
        internal static int colsupNo_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupNo.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prodcut Name.
        /// </summary>
        internal static string colsupPrdName_Caption {
            get {
                return ResourceManager.GetString("colsupPrdName.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price .
        /// </summary>
        internal static string colsupPrice_Caption {
            get {
                return ResourceManager.GetString("colsupPrice.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        internal static string colsupQuanMain_Caption {
            get {
                return ResourceManager.GetString("colsupQuanMain.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 2.
        /// </summary>
        internal static int colsupRefNo_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupRefNo.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Boolean similar to True.
        /// </summary>
        internal static bool colsupStatus_Visible {
            get {
                object obj = ResourceManager.GetObject("colsupStatus.Visible", resourceCulture);
                return ((bool)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 11.
        /// </summary>
        internal static int colsupStatus_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupStatus.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Percent.
        /// </summary>
        internal static string colsupTaxPercent_Caption {
            get {
                return ResourceManager.GetString("colsupTaxPercent.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 6.
        /// </summary>
        internal static int colsupTaxPrice_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupTaxPrice.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax.
        /// </summary>
        internal static string colsupTaxPriceSub_Caption {
            get {
                return ResourceManager.GetString("colsupTaxPriceSub.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 4.
        /// </summary>
        internal static int colsupTotal_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupTotal.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 8.
        /// </summary>
        internal static int colsupTotalFinal_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupTotalFinal.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Int32 similar to 5.
        /// </summary>
        internal static int colsupTotalFrgn_VisibleIndex {
            get {
                object obj = ResourceManager.GetObject("colsupTotalFrgn.VisibleIndex", resourceCulture);
                return ((int)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tax Percent.
        /// </summary>
        internal static string colTaxPercent_Caption {
            get {
                return ResourceManager.GetString("colTaxPercent.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Tax.
        /// </summary>
        internal static string colTaxPrice_Caption {
            get {
                return ResourceManager.GetString("colTaxPrice.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string colTotal_Caption {
            get {
                return ResourceManager.GetString("colTotal.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total After Discount.
        /// </summary>
        internal static string colTotalAfterDiscount_Caption {
            get {
                return ResourceManager.GetString("colTotalAfterDiscount.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount Forign Currency.
        /// </summary>
        internal static string colTotalFrgn_Caption {
            get {
                return ResourceManager.GetString("colTotalFrgn.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete expired items No : {0}?.
        /// </summary>
        internal static string delPrdExpirMssg {
            get {
                return ResourceManager.GetString("delPrdExpirMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Expired items document number: {0} has been deleted successfully..
        /// </summary>
        internal static string delPrdExpirSuccessMssg {
            get {
                return ResourceManager.GetString("delPrdExpirSuccessMssg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discount.
        /// </summary>
        internal static string gridColumn1_Caption {
            get {
                return ResourceManager.GetString("gridColumn1.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string gridColumn2_Caption {
            get {
                return ResourceManager.GetString("gridColumn2.Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton46_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton46.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton47_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton47.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton48_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton48.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolStripButton49_Image {
            get {
                object obj = ResourceManager.GetObject("toolStripButton49.Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Size similar to {Width=111, Height=57}.
        /// </summary>
        internal static System.Drawing.Size toolStripLabel1_Size {
            get {
                object obj = ResourceManager.GetObject("toolStripLabel1.Size", resourceCulture);
                return ((System.Drawing.Size)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice number.
        /// </summary>
        internal static string toolStripLabel1_Text {
            get {
                return ResourceManager.GetString("toolStripLabel1.Text", resourceCulture);
            }
        }
    }
}
